services:
  - type: web
    name: datavault-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_api:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: API_PORT
        value: 10000
      - key: API_BASE_URL
        sync: false # Will be set manually in Render dashboard
      - key: SUPABASE_URL
        sync: false # Will be set manually in Render dashboard
      - key: SUPABASE_KEY
        sync: false # Will be set manually in Render dashboard 